Add third_party/catapult.
For the following error:

$ gn gen out/Default/
ERROR at //build/config/android/rules.gni:2619:9: Script returned non-zero exit code.
        exec_script("//build/android/gyp/aar.py",
        ^----------
Current dir: /media/data/MyProjects/chromium-net-independent/out/Default/
Command: python -- /media/data/MyProjects/chromium-net-independent/build/android/gyp/aar.py --input-file ../../../../../../home/hanpfei0306/data/dev_tools/Android/sdk/extras/android/m2repository/com/android/support/design/24.1.1/design-24.1.1.aar --list
Returned 1.
stderr:

Traceback (most recent call last):
  File "/media/data/MyProjects/chromium-net-independent/build/android/gyp/aar.py", line 15, in <module>
    from util import build_utils
  File "/media/data/MyProjects/chromium-net-independent/build/android/gyp/util/build_utils.py", line 24, in <module>
    from pylib.constants import host_paths
  File "/media/data/MyProjects/chromium-net-independent/build/android/gyp/util/../../pylib/constants/__init__.py", line 17, in <module>
    import devil.android.sdk.keyevent
ImportError: No module named devil.android.sdk.keyevent

See //third_party/android_tools/BUILD.gn:46:1: whence it was called.
android_aar_prebuilt("android_support_design_java") {
^----------------------------------------------------
See //build/config/android/internal_rules.gni:140:23: which caused the file to be included.
            deps += [ "${_target_label}__build_config" ]
                      ^-------------------------------

Signed-off-by: Pengfei Han <hanpfei@gmail.com>